var mongoose = require('mongoose');
var Schema = mongoose.Schema;

/* application form model */
var applicationFormSchema = new Schema({
    //personal details
    category: { type: String, lowercase: true, trim: true },
    course: { type: String, lowercase: true, trim: true },
    fullname: { type: String, lowercase: true, trim: true },
    dob: { type: String, lowercase: true, trim: true },
    firstname: { type: String, lowercase: true, trim: true },
    middlename: { type: String, lowercase: true, trim: true },
    lastname: { type: String, lowercase: true, trim: true },
    gender: { type: String, lowercase: true, trim: true },
    mstatus: { type: String, lowercase: true, trim: true },
    pob: { type: String, lowercase: true, trim: true },
    nationality: { type: String, lowercase: true, trim: true },
    religion: { type: String, lowercase: true, trim: true },
    subcaste: { type: String, lowercase: true, trim: true },
    mothertongue: { type: String, lowercase: true, trim: true },
    aadhar: { type: String, lowercase: true, trim: true },
    bloodgroup: { type: String, lowercase: true, trim: true },
    phoneno: { type: String, lowercase: true, trim: true },
    email: { type: String, lowercase: true, trim: true },
    telephpne: { type: String, lowercase: true, trim: true },
    sports: { type: String, lowercase: true, trim: true },
    extracurricular: { type: String, lowercase: true, trim: true },
    disability : { type: String, lowercase: true, trim: true },
    fname : { type: String, lowercase: true, trim: true },
    fqualification : { type: String, lowercase: true, trim: true },
    foccupation : { type: String, lowercase: true, trim: true },
    fincome : { type: String, lowercase: true, trim: true },
    fmobile : { type: String, lowercase: true, trim: true },
    mname : { type: String, lowercase: true, trim: true },
    mqualification : { type: String, lowercase: true, trim: true },
    moccupation : { type: String, lowercase: true, trim: true },
    mmobile : { type: String, lowercase: true, trim: true },
    guardian_name : { type: String, lowercase: true, trim: true },
    guardian_qualification : { type: String, lowercase: true, trim: true },
    guardian_occupation : { type: String, lowercase: true, trim: true },
    guardian_mobileno : { type: String, lowercase: true, trim: true },

    //Education
    ssc : { type: String, lowercase: true, trim: true },
    board : { type: String, lowercase: true, trim: true },
    sc : { type: String, lowercase: true, trim: true },
    py : { type: String, lowercase: true, trim: true },
    mo : { type: String, lowercase: true, trim: true },
    moo : { type: String, lowercase: true, trim: true },
    percentage : { type: String, lowercase: true, trim: true },
    seatn : { type: String, lowercase: true, trim: true },
    hsc : { type: String, lowercase: true, trim: true },
    board1 : { type: String, lowercase: true, trim: true },
    sc1 : { type: String, lowercase: true, trim: true },
    py1 : { type: String, lowercase: true, trim: true },
    mo1 : { type: String, lowercase: true, trim: true },
    moo1 : { type: String, lowercase: true, trim: true },
    percentage1 : { type: String, lowercase: true, trim: true },
    seatn1 : { type: String, lowercase: true, trim: true },
    sem1 : { type: String, lowercase: true, trim: true },
    board2 : { type: String, lowercase: true, trim: true },
    sc2 : { type: String, lowercase: true, trim: true },
    mp2 : { type: String, lowercase: true, trim: true },
    percentage2 : { type: String, lowercase: true, trim: true },
    grade : { type: String, lowercase: true, trim: true },
    sem2 : { type: String, lowercase: true, trim: true },
    board3 : { type: String, lowercase: true, trim: true },
    sc3 : { type: String, lowercase: true, trim: true },
    mp3 : { type: String, lowercase: true, trim: true },
    percentage3 : { type: String, lowercase: true, trim: true },
    grade1 : { type: String, lowercase: true, trim: true },
    

    //Address
    room : { type: String, lowercase: true, trim: true },
    country : { type: String, lowercase: true, trim: true },
    state: { type: String, lowercase: true, trim: true },
    district: { type: String, lowercase: true, trim: true },
    city: { type: String, lowercase: true, trim: true },
    pincode: { type: String, lowercase: true, trim: true },
    room1 : { type: String, lowercase: true, trim: true },
    country1 : { type: String, lowercase: true, trim: true },
    state1: { type: String, lowercase: true, trim: true },
    district1: { type: String, lowercase: true, trim: true },
    city1: { type: String, lowercase: true, trim: true },
    pincode1: { type: String, lowercase: true, trim: true },
    
    //Document upload & Photo,sign
    aadhar1: { type: String, lowercase: true, trim: true },
    rationcard: { type: String, lowercase: true, trim: true },
    firstterm: { type: String, lowercase: true, trim: true },
    secondterm: { type: String, lowercase: true, trim: true },

    signature: { type: String, lowercase: true, trim: true },
    picture: { type: String, lowercase: true, trim: true },
    accept_terms: { type: Boolean, default: false },

    updated_at: { type: Date, default: Date.now },
    status: { type: Boolean, default: true },
    status: { type: Boolean, default: true },
    user: { type: Schema.Types.ObjectId, ref: 'Users' },
});

module.exports = User = mongoose.model('ApplicationForm', applicationFormSchema);